"""add system_notification table

Revision ID: 00c956ee44d8
Revises: c5d9c4ccc638
Create Date: 2025-09-26 17:08:01.992173

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c956ee44d8'
down_revision = 'c5d9c4ccc638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_notification',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('msg_type', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('created_by', models.types.StringUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', models.types.StringUUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='system_notification_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_notification')
    # ### end Alembic commands ###
