"""add publish_application and publish_application_history table

Revision ID: c5d9c4ccc638
Revises: b95962a3885c
Create Date: 2025-09-26 10:56:41.206411

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d9c4ccc638'
down_revision = 'b95962a3885c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_application',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('applicant_id', models.types.StringUUID(), nullable=False),
    sa.Column('applicant_area', sa.String(length=100), nullable=True),
    sa.Column('project_space_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('need_sys_approve', sa.Boolean(), nullable=True),
    sa.Column('region_admin_id', models.types.StringUUID(), nullable=True),
    sa.Column('sys_admin_id', models.types.StringUUID(), nullable=True),
    sa.Column('apply_app_version_id', models.types.StringUUID(), nullable=False),
    sa.Column('apply_app_type', sa.Integer(), nullable=False),
    sa.Column('created_by', models.types.StringUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', models.types.StringUUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='publish_application_pkey')
    )
    with op.batch_alter_table('publish_application', schema=None) as batch_op:
        batch_op.create_index('publish_application_applicant_id_idx', ['applicant_id'], unique=False)

    op.create_table('publish_application_history',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('application_id', models.types.StringUUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('operator_id', models.types.StringUUID(), nullable=True),
    sa.Column('operator_role', sa.String(length=100), nullable=True),
    sa.Column('from_status', sa.String(length=100), nullable=True),
    sa.Column('to_status', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='publish_application_history_pkey')
    )
    with op.batch_alter_table('publish_application_history', schema=None) as batch_op:
        batch_op.create_index('publish_application_history_application_id_idx', ['application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_application_history', schema=None) as batch_op:
        batch_op.drop_index('publish_application_history_application_id_idx')

    op.drop_table('publish_application_history')
    with op.batch_alter_table('publish_application', schema=None) as batch_op:
        batch_op.drop_index('publish_application_applicant_id_idx')

    op.drop_table('publish_application')
    # ### end Alembic commands ###
