"""add publish workflows and app_model_configs table

Revision ID: d31ad21855ff
Revises: 00c956ee44d8
Create Date: 2025-09-28 09:34:00.541257

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31ad21855ff'
down_revision = '00c956ee44d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_app_model_configs',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('configs', sa.JSON(), nullable=True),
    sa.Column('created_by', models.types.StringUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', models.types.StringUUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('opening_statement', sa.Text(), nullable=True),
    sa.Column('suggested_questions', sa.Text(), nullable=True),
    sa.Column('suggested_questions_after_answer', sa.Text(), nullable=True),
    sa.Column('speech_to_text', sa.Text(), nullable=True),
    sa.Column('text_to_speech', sa.Text(), nullable=True),
    sa.Column('more_like_this', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('user_input_form', sa.Text(), nullable=True),
    sa.Column('dataset_query_variable', sa.String(length=255), nullable=True),
    sa.Column('pre_prompt', sa.Text(), nullable=True),
    sa.Column('agent_mode', sa.Text(), nullable=True),
    sa.Column('sensitive_word_avoidance', sa.Text(), nullable=True),
    sa.Column('retriever_resource', sa.Text(), nullable=True),
    sa.Column('prompt_type', sa.String(length=255), server_default=sa.text("'simple'::character varying"), nullable=False),
    sa.Column('chat_prompt_config', sa.Text(), nullable=True),
    sa.Column('completion_prompt_config', sa.Text(), nullable=True),
    sa.Column('dataset_configs', sa.Text(), nullable=True),
    sa.Column('external_data_tools', sa.Text(), nullable=True),
    sa.Column('file_upload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='publish_app_model_configs_pkey')
    )
    with op.batch_alter_table('publish_app_model_configs', schema=None) as batch_op:
        batch_op.create_index('publish_app_app_id_idx', ['app_id'], unique=False)

    op.create_table('publish_workflows',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('marked_name', sa.String(), server_default='', nullable=False),
    sa.Column('marked_comment', sa.String(), server_default='', nullable=False),
    sa.Column('graph', sa.Text(), nullable=False),
    sa.Column('features', sa.TEXT(), nullable=False),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', models.types.StringUUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('environment_variables', sa.Text(), server_default='{}', nullable=False),
    sa.Column('conversation_variables', sa.Text(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name='publish_workflows_pkey')
    )
    with op.batch_alter_table('publish_workflows', schema=None) as batch_op:
        batch_op.create_index('publish_workflows_version_idx', ['tenant_id', 'app_id', 'version'], unique=False)

    with op.batch_alter_table('publish_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply_app_id', models.types.StringUUID(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_application', schema=None) as batch_op:
        batch_op.drop_column('apply_app_id')

    with op.batch_alter_table('publish_workflows', schema=None) as batch_op:
        batch_op.drop_index('publish_workflows_version_idx')

    op.drop_table('publish_workflows')
    with op.batch_alter_table('publish_app_model_configs', schema=None) as batch_op:
        batch_op.drop_index('publish_app_app_id_idx')

    op.drop_table('publish_app_model_configs')
    # ### end Alembic commands ###
